# config.yaml

######################################
# Azure model configuration          #
######################################
model_config: &client
  provider: AzureOpenAIChatCompletionClient
  config:
    model: gpt-4o-2024-11-20
    azure_endpoint: "https://evaln-openai.openai.azure.com/"
    azure_deployment: "gpt-4o"
    api_version: "2024-05-01-preview"
    api_key: "<key>"
    max_retries: 10

##########################
# Clients for each agent #
##########################
orchestrator_client: *client
coder_client: *client
web_surfer_client: *client
file_surfer_client: *client
action_guard_client: *client